
# Site settings

url: "http://ocesaulo.github.io"
baseurl: /ocesaulo_personal
google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "Saulo Soares"
lang: "en"
title: "OCESAULO"
#favicon: "/img/favicon.ico"
favicon: ""
description: "Website and blog of Saulo. Opinions expressed are mine."
keywords: "ocesaulo, blog, personal"

################
# Intro layout #
################

#black-favicon: "/img/black-lab-glass.ico"
black-favicon: ""
background-img: "../img/067-DSC03281.jpg"
me-img: "/img/spam.png"

########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "ocesaulo"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "/img/best_gif.gif"

##################
# Contact layout #
##################

email: "ocesaulo@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://ocesaulo.github.io/"
  - title: "linkedin"
    url: "http://no.linkedin.com/"
  - title: "youtube"
    url: "http://youtube.com/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables bellow this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
